/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountBox: typeof import('./src/components/Navigator/AccountBox.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Box: typeof import('./src/components/Box.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    FooterLinks: typeof import('./src/components/Footer/FooterLinks.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    JoinUs: typeof import('./src/components/JoinUs.vue')['default']
    Languages: typeof import('./src/components/Footer/Languages.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MiniProfile: typeof import('./src/components/Navigator/MiniProfile.vue')['default']
    MyAccount: typeof import('./src/components/MyAccount.vue')['default']
    Navigation: typeof import('./src/components/Navigator/Navigation.vue')['default']
    NewsletterSubscribe: typeof import('./src/components/Footer/NewsletterSubscribe.vue')['default']
    RegistrationForm: typeof import('./src/components/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Socials: typeof import('./src/components/Footer/Socials.vue')['default']
    Terms: typeof import('./src/components/Footer/Terms.vue')['default']
  }
}
